version: '3.8'

services:

  final:
    image: helloworld:part5
    container_name: final
    user: root

  nginx-proxied:
    image: nginx:latest
    container_name: nginx-proxied
    depends_on:
      - final
    ports:
      - "80:8080" # замапили 8080 порт через 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro